# Generated by Django 2.1.2 on 2018-10-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPlusImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.PositiveSmallIntegerField()),
                ('refno', models.PositiveSmallIntegerField()),
                ('idate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journal_type', models.CharField(max_length=20)),
                ('tran_type', models.CharField(max_length=2)),
                ('auth_no', models.CharField(max_length=20)),
                ('card_type', models.CharField(max_length=10)),
                ('reconciled', models.BooleanField()),
                ('batch_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CHSImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.PositiveSmallIntegerField()),
                ('refno', models.PositiveSmallIntegerField()),
                ('idate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journal_type', models.CharField(max_length=20)),
                ('tran_type', models.CharField(max_length=2)),
                ('auth_no', models.CharField(max_length=20)),
                ('card_type', models.CharField(max_length=10)),
                ('reconciled', models.BooleanField()),
                ('batch_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Depts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_no', models.CharField(max_length=2, unique=True)),
                ('dept_base', models.CharField(max_length=2)),
                ('dept_description', models.CharField(max_length=30)),
                ('merchant_id', models.CharField(max_length=10)),
                ('tran_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('import_ap', models.BooleanField()),
                ('import_chs', models.BooleanField()),
                ('closed', models.BooleanField()),
                ('gl_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
