# Generated by Django 2.1.2 on 2018-10-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_auto_20181012_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='import_ap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='import_chs',
            field=models.BooleanField(default=False),
        ),
    ]
