# Generated by Django 2.1.2 on 2018-10-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0005_auto_20181022_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountsPlusImport',
            new_name='Transactions',
        ),
        migrations.DeleteModel(
            name='CHSImport',
        ),
    ]
