# Generated by Django 2.1.2 on 2018-10-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0007_auto_20181023_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.PositiveSmallIntegerField()),
                ('refno', models.PositiveSmallIntegerField()),
                ('idate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journal_type', models.CharField(max_length=20)),
                ('tran_type', models.CharField(max_length=2)),
                ('auth_no', models.CharField(max_length=20)),
                ('card_type', models.CharField(max_length=10)),
                ('reconciled', models.BooleanField()),
                ('batch_date', models.DateField()),
            ],
        ),
    ]
